apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-app
  namespace: staging
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 123456789012.dkr.ecr.ca-central-1.amazonaws.com/mon-app:{TAG}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
